### PR TITLE
Huawei-cbs certification

### PR DESCRIPTION
**Pull request by helloworld-sj**
## Pre-submission checklist:

Please check each of these after submitting your pull request:

- [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/cnf-certification/blob/main/Certified_CNF_Form.md)?
- [x] Did you include the product/project logo in SVG, EPS or AI format?
- [x] Does your logo clearly state the name of the product/project/org and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
- [ ] If your product/project is open source, did you include the repo_url?
- [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by agentpoyo** [comment]
### Technical Acceptance Criteria

- [ ] README.md is present.
- [ ] cnf-testsuite.yml is present and valid.
- [ ]  Results file cnf-testsuite-results-YYYY-MMDD-HHMMSS-NNN.yml found.
- [ ] PRODUCT.yaml has valid fields populated (unless optional):
  - [ ] vendor name
  - [ ] name
  - [ ] version of the product
  - [ ] website url - URL to prodct
  - [ ] repo_url - URL to the product (optional)
  - [ ] documentation_url - URL to the product docs (optional)
  - [ ] product_log_url - URL to the product logo (optional)
  - [ ] type - Type of application (optional)
  - [ ] description - Brief description of the product.

Only the essential tests pasted below:

**Review by agentpoyo — APPROVED** [review]
LGTM; passes technical requirements.

**Comment by helloworld-sj** [comment]
Hi, what should I do for the next step of this PR? @lixuna @taylor

**Comment by lixuna** [comment]
**[Policy Requirements](https://github.com/cncf/cnf-certification/blob/main/reviewing.md#policy-requirements)**

- [ ] Confirm that the vendor is currently a member of CNCF
- [ ] Review the PRODUCT.yaml file, and:
- [ ] Verify that there is a Participation Form on file for the vendor, and that the vendor is in good standing in the program.
- [ ] Verify the product name, product version and website_url are listed in the "Qualifying Offerings" section of the vendor's Participation Form.

**[Tasks to Complete After Review](https://github.com/cncf/cnf-certification/blob/main/reviewing.md#tasks-to-complete-after-review)**
- [ ] Update the Certified CNF spreadsheet to reflect the vendor's certified offering.
- [ ] Add the vendor's information to the CNCF landscape which also causes them to appear on https://www.cncf.io/certification/cnf.
- [ ] Add a comment saying "This product is now a "Certified CNF".
- [ ] Merge the PR (eg. Squad and merge).
- [ ] Close the PR.

**Comment by lixuna** [comment]
LGTM; passes policy requirements. I will send a request to CNCF to add this CNF to [l.cncf.io](https://landscape.cncf.io/card-mode?category=certified-cn-fs&grouping=category).

**Comment by lixuna** [comment]
@helloworld-sj This product is now a "Certified CNF"

CNF is listed at:
- https://landscape.cncf.io/card-mode?category=certified-cn-fs&grouping=category
- https://www.cncf.io/certification/cnf/#logos

Certified CNF mark and brand guide are available at https://github.com/cncf/artwork/tree/master/other/certified-cnf.

**Pull request merged**
