### PR TITLE
v1.0-beta/cSRX

### PR DESCRIPTION
**Pull request by hamidiridha**
## Pre-submission checklist:

Please check each of these after submitting your pull request:

- [ ] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/cnf-certification/blob/main/Certified_CNF_Form.md)?
- [ ] Did you include the product/project logo in SVG, EPS or AI format?
- [ ] Does your logo clearly state the name of the product/project/org and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
- [ ] If your product/project is open source, did you include the repo_url?
- [ ] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by hamidiridha** [comment]
[README.md](https://github.com/cncf/cnf-certification/files/9782357/README.md)

**Comment by hamidiridha** [comment]
[cnf-testsuite-results-20220701-164229-572.yml.md](https://github.com/cncf/cnf-certification/files/9782377/cnf-testsuite-results-20220701-164229-572.yml.md)
[cnf-testsuite.yml.md](https://github.com/cncf/cnf-certification/files/9782378/cnf-testsuite.yml.md)
[csrx.yaml.md](https://github.com/cncf/cnf-certification/files/9782379/csrx.yaml.md)
cSRX-Logo

**Comment by hamidiridha** [comment]
[cnf-testsuite-results-20220701-164229-572.yml.md](https://github.com/cncf/cnf-certification/files/9782401/cnf-testsuite-results-20220701-164229-572.yml.md)
[cnf-testsuite.yml.md](https://github.com/cncf/cnf-certification/files/9782402/cnf-testsuite.yml.md)
[csrx.yaml.md](https://github.com/cncf/cnf-certification/files/9782403/csrx.yaml.md)
[README.md](https://github.com/cncf/cnf-certification/files/9782404/README.md)
cSRX-Logo
Signed-off-by: Ridha Hamidi <rhamidi@juniper.net>

**Comment by hamidiridha** [comment]
[Certified_CNF_Form.md](https://github.com/cncf/cnf-certification/files/9782596/Certified_CNF_Form.md)
Signed-off-by: Ridha Hamidi <mailto:rhamidi@juniper.net>

**Comment by agentpoyo** [comment]
- [ ] README.md is present.
- [ ] cnf-testsuite.yml is present and valid.
- [ ]  Results file cnf-testsuite-results-YYYY-MMDD-HHMMSS-NNN.yml found.
- [ ] PRODUCT.yaml has valid fields populated (unless optional):
  - [ ] vendor name
  - [ ] name
  - [ ] version of the product
  - [ ] website url - URL to prodct
  - [ ] repo_url - URL to the product (optional)
  - [ ] documentation_url - URL to the product docs (optional)
  - [ ] product_log_url - URL to the product logo (optional)
  - [ ] type - Type of application (optional)
  - [ ] description - Brief description of the product.

Essential Tests passed: x of 15

```
essential tests from results here
```

**Review by agentpoyo — APPROVED** [review]
LGTM, 10 of 14 essentials passes technical requirements.

**Comment by taylor** [comment]
> [cnf-testsuite-results-20220701-164229-572.yml.md](https://github.com/cncf/cnf-certification/files/9782401/cnf-testsuite-results-20220701-164229-572.yml.md) [cnf-testsuite.yml.md](https://github.com/cncf/cnf-certification/files/9782402/cnf-testsuite.yml.md) [csrx.yaml.md](https://github.com/cncf/cnf-certification/files/9782403/csrx.yaml.md) [README.md](https://github.com/cncf/cnf-certification/files/9782404/README.md) cSRX-Logo Signed-off-by: Ridha Hamidi [rhamidi@juniper.net](mailto:rhamidi@juniper.net)

files need to be sent as commits into the directory and not via a comment.

**Comment by agentpoyo** [comment]
#### Technical Acceptance Criteria Checks

- [ ] README.md is present.
- [ ] cnf-testsuite.yml is present and valid.
- [ ]  Results file cnf-testsuite-results-YYYY-MMDD-HHMMSS-NNN.yml found.
- [ ] PRODUCT.yaml has valid fields populated (unless optional):
  - [ ] vendor name
  - [ ] name
  - [ ] version of the product
  - [ ] website url - URL to prodct
  - [ ] repo_url - URL to the product (optional)
  - [ ] documentation_url - URL to the product docs (optional)
  - [ ] product_log_url - URL to the product logo (optional)
  - [ ] type - Type of application (optional)
  - [ ] description - Brief description of the product.

Essential Tests passed: 12 of 14:

```
results go here
```

**Review by agentpoyo — APPROVED** [review]
LGTM for cSRX PR

**Comment by lixuna** [comment]
## Policy Requirements
- [x] Confirm that the vendor is currently a member of CNCF - Yes, Juniper is a Silver member
- [ ] Verify that there is a Participation Form on file for the vendor, and that the vendor is in good standing in the program.
- [ ] Verify the product name, product version and website_url are listed in the "Qualifying Offerings" section of the vendor's Participation Form.

Next steps:

- [ ] Signed participation form needed via DocuSign link: https://na4.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=cb6ee2b7-ee9d-48c5-b154-abfab626a21f&env=na4&acct=99530ead-94da-4299-b0ca-9df20e86a064&v=2

**Comment by lixuna** [comment]
## Policy Requirements
- [x] Confirm that the vendor is currently a member of CNCF - Yes, Juniper is a Silver member
- [x] Verify that there is a Participation Form on file for the vendor, and that the vendor is in good standing in the program.
- [x] Verify the product name, product version and website_url are listed in the "Qualifying Offerings" section of the vendor's Participation Form.

This product is now a "Certified CNF"

**Review by lixuna — COMMENTED** [review]
LGTM

**Comment by lixuna** [comment]
@taylor please review and merge

**Comment by taylor** [comment]
Lgtm

**Pull request merged**
