### PR TITLE
CNF Certification results for 16.2.0/lighty-rcgnmi-app

### PR DESCRIPTION
**Pull request by PeterSuna**
New release lighty 16.2.0 contains fixed failing tests from previous report:
[#1562](https://github.com/cncf/cnf-testsuite/issues/1562)

From provided [CNF testsuite configuration](https://github.com/cncf/cnf-testsuite/blob/main/CNF_TESTSUITE_YML_USAGE.md) I was not able to configure testsuite to use specific lighty-rcgnmi-app version from published [helm repository](https://github.com/PANTHEONtech/helm-charts). (With configuration from [#1562](https://github.com/cncf/cnf-testsuite/issues/1562) it takes version 16.1.0)
e.g.: `helm install lighty-rcgnmi-app pantheon-helm-repo/lighty-rcgnmi-app-helm --version 16.2.0`.
 If there is a way how to do it, feel free to guide me or fix it directly in PR.

Thanks.

## Pre-submission checklist:

Please check each of these after submitting your pull request:

- [x] If this is a new entry, have you submitted a signed [participation form](https://github.com/cncf/cnf-certification/blob/main/Certified_CNF_Form.md)?
- [x] Did you include the product/project logo in SVG, EPS or AI format?
- [x] Does your logo clearly state the name of the product/project/org and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
- [x] If your product/project is open source, did you include the repo_url?
- [x] Did you copy and paste the [installation and configuration instructions](https://github.com/cncf/k8s-conformance/blob/master/faq.md#can-i-provide-a-link-to-the-installation-directions) into the README.md file in addition to linking to them?

### CODE REVIEW

**Comment by agentpoyo** [comment]
- [ ] README.md is present.
- [ ] cnf-testsuite.yml is present and valid.
- [ ]  Results file cnf-testsuite-results-YYYY-MMDD-HHMMSS-NNN.yml found.
- [ ] PRODUCT.yaml has valid fields populated (unless optional):
  - [ ] vendor name
  - [ ] name
  - [ ] version of the product
  - [ ] website url - URL to prodct
  - [ ] repo_url - URL to the product (optional)
  - [ ] documentation_url - URL to the product docs (optional)
  - [ ] product_log_url - URL to the product logo (optional)
  - [ ] type - Type of application (optional)
  - [ ] description - Brief description of the product.

Essential Tests passed: x of x

```
list of essential tests go here
```

**Review by agentpoyo — APPROVED** [review]
Looks good to me. Meets essential tests passed for certification and meets technical requirements for PR.

**Comment by lixuna** [comment]
To do: updated participation forms needed for v16.1

**Comment by agentpoyo** [comment]
Updates look good for the new version change on technical side. @lixuna

**Comment by lixuna** [comment]
Policy Requirements - LGTM
- [x] Confirm that the vendor is currently a member of CNCF
- [x] Verify that there is a Participation Form on file for the vendor, and that the vendor is in good standing in the program.
- [x] Verify the product name, product version and website_url are listed in the "Qualifying Offerings" section of the vendor's Participation Form.

**Comment by lixuna** [comment]
This product is now a "Certified CNF"

**Comment by denverwilliams** [comment]
@PeterSuna Hi Peter, we've update our documentation to include how to set a non-default helm chart version. You can follow the steps [here](https://github.com/cncf/cnf-testsuite/pull/1656/files) and should be able to set your helm chart version.

**Pull request merged**
